apiVersion: v1
kind: Service
metadata:
  name: {{lower .Values.name}}-{{lower .Values.subdomain}}-service
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: {{lower .Values.name}}-{{lower .Values.subdomain}}-api
      protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.serviceTargetPort }} 
  selector:
    app: {{lower .Values.name}}-{{lower .Values.subdomain}}
