apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: ingress-router-{{ lower .Values.name }}-{{ lower .Values.project_domain }}
 annotations:
   kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{lower .Values.project_domain }}.{{lower .Values.lab_subdomain }}.harnessevents.com
    http:
     paths:
     - pathType: ImplementationSpecific
       backend:
          service:
             name: {{lower .Values.name}}-{{lower .Values.project_domain}}-service
             port:
               number: 8080
